#ifndef EXCEPTIONS_H
#define EXCEPTIONS_H

enum Exception {
	EDGE_ALREADY_EXISTS,
	EDGE_DOES_NOT_EXIST,	
	NODE_ALREADY_EXISTS,
	NODE_DOES_NOT_EXIST,
	SOURCE_NODE_DOES_NOT_EXIST,
	DESTINATION_NODE_DOES_NOT_EXIST,
};

#endif
